apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-19-awareness-website-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: covid-19-awareness
  template:
    metadata:
      labels:
        app: covid-19-awareness
    spec:
      containers:
      - name: covid-19-awareness
        image: yash5090/covid-19-awareness:latest
        ports:
        - containerPort: 5000
